### PR TITLE
Demo with Docker & Docker Compose

### PR DESCRIPTION
**Pull request by disarticulate**
Simple demo for the stand alone script. Can easily run pub/sub scripts. Can even scale both consumer and publisher:

```
docker-compose up --scale consumer=3 --scale ui=1 --scale publisher=1
```

Should help people visualize the ui system and provide dev feedback.

### CODE REVIEW

**Comment by sagivf** [comment]
Awesome @disarticulate this looks great! I'll give it a spin in the following week or two and merge it in.
Thanks for helping out :smile:

**Comment by disarticulate** [comment]
The only thing that needs to be documented is the environment variables when you run docker-compose. Most people know how it works.

**Comment by sagivf** [comment]
@disarticulate I'm not particularly experienced with docker. Perhaps you can help me out.

a) I need to change the version to "2" - it tells me "3" is not supported.
b) I'm having a hard time with the environment variables. Using `docker run -e DB_HOST="172.20.0.1" rjqui_ui` doesn't seem to work.

**Comment by disarticulate** [comment]
environment variables are set in your shell for docker-compose version 3

You may have to ger the latest version on the docker website for both
docker and docker-compse.

prior to version 3, you couldn't use env variable substitution in the yml
file, which complicates.

if 2, you have to either mount an .env in docker-compose or hard code the
$variables in the yml

**Comment by disarticulate** [comment]
I think the issue is you have to open up the port in docker-compose.

so if you're starting a docker container for one of the sub/pub, you need to expose the port
```
docker -p $PORT
```
Let me fix the docker file to use open the port (it's hardcoded as 12001

**Comment by sagivf** [comment]
@disarticulate your right, thanks, I used apt-get and got the wrong docker-compose version. using pip works.
I'm still confused how to connect to a database.
I'm trying to connect to one running on my local machine - `sudo ip addr show docker0` gives me an IP. I set that - `export DB_HOST=172.17.0.1`. Looks like the rjqui_ui container is trying to connect but failing - 
```
\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"172.17.0.1\",\"port\":28015}.","isOperational":true}
```
Maybe I need to open up port 28015 or something?

**Comment by disarticulate** [comment]
When I set it up, my host was external to the docker environment, so I opened up the port $DB_PORT

If you want to run a docker-compose service for rethinkdb:
```
  rethinkdb:
    hostname: rethinkdb
    build:
      context: .
      dockerfile: Dockerfile.rethinkdb
    ports:
      - '28015:28015'
```
the Dockerfile.rethinkdb would be like:
```
FROM rethinkdb
ENTRYPOINT [ "rethinkdb",  "--bind", "all"]
```
With the above, $DB_HOST would be set to rethinkdb as DNS and routing inside docker is internal unless you specify open ports or other networking

**Comment by sagivf** [comment]
I got it working, this docker stuff can be fun :smile: 
I had to remove the DB_USER and DB_PASSWORD and set DB_NAME, otherwise it sends an empty string which throws errors. Any way no to send them when empty or maybe send null? Would be nice to get it working with default configuration.

Also, is it easy to open my local host database 28015 port? I'm using ubuntu and couldn't find anything on google that works.

**Comment by disarticulate** [comment]
If you want to set it defaults you'd modify the ui entry point?
```
    entrypoint:
       - node
       - /app/bin/www
       - -d
       - $DB_NAME
       - -s
       - $DB_HOST
       - -i 
       - $DB_PORT
       - -p 
       - "3000"
```
For opening ports, docker and docker-compose basically erradicate your firewall, so you added to 
```-p "28015:28015"```
for docker-compose it's
```
ports:
  - "28015:28015"
```
which is making ```internal_port:external_port```

**Comment by sagivf** [comment]
@disarticulate Added some self documentation and .env file. Thank a lot for the pull request, now just need to find the time to make this project something worthwhile.

**Comment by disarticulate** [comment]
glad I could assist.

**Pull request merged**
